CREATE TABLE IF NOT EXISTS dialects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS word_dialects (
    word_id UUID NOT NULL REFERENCES words(id) ON DELETE CASCADE,
    dialect_id UUID NOT NULL REFERENCES dialects(id) ON DELETE CASCADE,
    PRIMARY KEY (word_id, dialect_id)
);
